import { StyleSheet } from "react-native";

import { color, fontFamily, fontSize, radius, space, wash } from "../../../shared/theme";

export const aiStyles = StyleSheet.create({
  root: {
    flex: 1,
    minWidth: 0,
    backgroundColor: color.background,
  },
  pageViewport: {
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },
  chatPage: {
    flex: 1,
    minHeight: 0,
  },
  historyPage: {
    flex: 1,
    minHeight: 0,
    backgroundColor: color.background,
  },
  historySearchInput: {
    marginHorizontal: space[3],
    marginTop: space[3],
    marginBottom: space[2],
    borderRadius: radius.control,
    backgroundColor: color.field,
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
  },
  historyList: {
    flex: 1,
    minHeight: 0,
  },
  historyListContent: {
    paddingBottom: space[3],
  },
  historyListContentEmpty: {
    flexGrow: 1,
    justifyContent: "center",
  },
  historyGroupLabel: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    fontWeight: "600",
    backgroundColor: color.background,
    paddingHorizontal: space[4],
    paddingTop: space[3],
    paddingBottom: space[1],
  },
  historyRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: color.border,
  },
  historyRowActive: {
    backgroundColor: wash.accentSoft,
  },
  historyRowMain: {
    flex: 1,
    minWidth: 0,
    alignSelf: "stretch",
    justifyContent: "center",
    gap: space[1],
    paddingLeft: space[3],
    paddingVertical: space[2],
  },
  historyRowTitleLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: space[1],
    minWidth: 0,
  },
  historyActiveMark: {
    width: 16,
    alignItems: "center",
  },
  historyRowTitle: {
    flex: 1,
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    fontWeight: "500",
  },
  historyRowMuted: {
    color: color.muted,
  },
  historyRowMetaLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: space[1],
    paddingLeft: 20,
    minWidth: 0,
  },
  historyBadge: {
    flexShrink: 0,
    borderRadius: radius.control,
    backgroundColor: color.field,
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    paddingHorizontal: space[1],
  },
  historyRowDetail: {
    flex: 1,
    minWidth: 0,
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  historyMoreButton: {
    width: 44,
    height: 44,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    marginRight: space[2],
    borderRadius: radius.control,
  },
  historyFooter: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: color.border,
    backgroundColor: color.surface,
    paddingHorizontal: space[4],
  },
  historyArchiveToggle: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: space[2],
  },
  historyCheckbox: {
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.control,
    borderWidth: 1,
    borderColor: color.accent,
    backgroundColor: color.background,
  },
  historyCheckboxChecked: {
    backgroundColor: color.accent,
  },
  historyFooterLabel: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
  },
  historyFooterCount: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: space[2],
    paddingHorizontal: space[4],
  },
  headerTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.md,
    fontWeight: "600",
  },
  subtitle: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    marginTop: 2,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: space[1],
  },
  list: {
    flex: 1,
  },
  pickerList: {
    flexGrow: 0,
    maxHeight: 520,
  },
  inlinePickerList: {
    maxHeight: 240,
  },
  listContent: {
    paddingHorizontal: space[4],
    paddingTop: space[3],
    paddingBottom: 180,
    gap: space[3],
  },
  empty: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    textAlign: "center",
    padding: space[6],
  },
  banner: {
    borderRadius: radius.panel,
    borderWidth: 1,
    borderColor: color.error,
    backgroundColor: wash.dangerSoft,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
  },
  bannerText: {
    color: color.error,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
  },
  warningBanner: {
    borderRadius: radius.panel,
    borderWidth: 1,
    borderColor: color.warning,
    backgroundColor: wash.accentSoft,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
  },
  warningText: {
    color: color.warning,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
  },
  userBubble: {
    alignSelf: "flex-end",
    maxWidth: "92%",
    backgroundColor: wash.accentSoft,
    borderRadius: radius.panel,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
  },
  assistantBlock: {
    alignSelf: "stretch",
    gap: space[2],
  },
  markdown: {
    gap: space[2],
  },
  paragraph: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.chat,
    lineHeight: 20,
  },
  heading1: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xl,
    fontWeight: "700",
    lineHeight: 28,
  },
  heading2: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.lg,
    fontWeight: "700",
    lineHeight: 24,
  },
  heading3: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.md,
    fontWeight: "700",
    lineHeight: 22,
  },
  strong: {
    fontWeight: "700",
  },
  emphasis: {
    fontStyle: "italic",
  },
  strikethrough: {
    textDecorationLine: "line-through",
  },
  inlineCode: {
    color: color.foreground,
    fontFamily: fontFamily.mono,
    backgroundColor: color.field,
    fontSize: fontSize.chat,
  },
  link: {
    color: color.accent,
    textDecorationLine: "underline",
  },
  blockquote: {
    borderLeftWidth: 3,
    borderLeftColor: color.accent,
    paddingLeft: space[3],
    gap: space[2],
  },
  listBlock: {
    gap: space[1],
  },
  listItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: space[2],
  },
  listMarker: {
    color: color.accent,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.chat,
    minWidth: 16,
  },
  listItemBody: {
    flex: 1,
    gap: space[1],
  },
  codeBlock: {
    width: "100%",
    maxHeight: 280,
    borderRadius: radius.panel,
    backgroundColor: color.crust,
  },
  codeContent: {
    width: "100%",
    padding: space[3],
  },
  codeText: {
    color: color.foreground,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.xs,
    lineHeight: 18,
  },
  thematicBreak: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: color.border,
  },
  tableCard: {
    minWidth: "100%",
    borderRadius: radius.panel,
    borderWidth: 1,
    borderColor: color.border,
    backgroundColor: color.surface,
    paddingHorizontal: space[2],
    paddingVertical: space[1],
  },
  tableCardRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: space[3],
    paddingVertical: space[2],
  },
  tableCardRowDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: color.border,
  },
  tableCardField: {
    flexGrow: 1,
    flexBasis: 140,
    gap: 2,
  },
  tableCardLabel: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    fontWeight: "500",
  },
  tableCardValue: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.chat,
    lineHeight: 20,
  },

  streamingCursor: {
    color: color.accent,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.chat,
  },

  messageText: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.chat,
    lineHeight: 20,
  },
  metaText: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  partCard: {
    borderRadius: radius.panel,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: color.border,
    backgroundColor: color.surface,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
    gap: space[1],
  },
  partTitle: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    fontWeight: "600",
  },
  rowActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: space[2],
    marginTop: space[1],
  },
  actionLabel: {
    color: color.accent,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    fontWeight: "600",
  },
  dangerLabel: {
    color: color.error,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    fontWeight: "600",
  },
  disclosure: {
    color: color.muted,
    fontSize: fontSize.sm,
    marginLeft: "auto",
  },
  workBlock: {
    borderRadius: radius.panel,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: color.border,
    backgroundColor: color.surface,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
    gap: space[2],
  },
  workHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: space[2],
    minWidth: 0,
  },
  workSummary: {
    flex: 1,
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  timeline: {
    gap: space[1],
    paddingLeft: space[1],
  },
  timelineRowBody: {
    position: "relative",
    paddingLeft: space[2],
  },
  timelineRowSpacing: {
    paddingBottom: space[1],
  },
  timelineRowHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: space[1],
    minHeight: 24,
  },
  timelineLabel: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    fontWeight: "600",
  },
  timelineSubject: {
    flex: 1,
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  timelineStatus: {
    color: color.accent,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  timelineDetail: {
    marginLeft: 26,
    paddingVertical: space[1],
    gap: space[1],
  },
  timelineLine: {
    position: "absolute",
    left: 10,
    top: 25,
    bottom: 0,
    width: StyleSheet.hairlineWidth,
    backgroundColor: color.border,
  },
  detailText: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    lineHeight: 18,
  },
  errorText: {
    color: color.error,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    lineHeight: 18,
  },
  elevatedCard: {
    borderRadius: radius.panel,
    borderWidth: 1,
    borderColor: color.border,
    backgroundColor: color.surface,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
    gap: space[2],
  },
  cardBody: { gap: space[2] },

  composerDock: {
    position: "absolute",
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1,
    paddingHorizontal: space[3],
    paddingBottom: space[3],
  },
  triggerPicker: {
    position: "absolute",
    right: space[3],
    bottom: "100%",
    left: space[3],
    zIndex: 2,
    elevation: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: color.border,
    borderRadius: radius.panel,
    backgroundColor: color.surface,
    shadowColor: color.crust,
    shadowOpacity: 0.4,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  triggerPickerTitle: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    fontWeight: "600",
    paddingHorizontal: space[4],
    paddingTop: space[2],
    paddingBottom: space[1],
  },
  composer: {
    borderWidth: 1,
    borderColor: color.border,
    borderRadius: radius.panel,
    padding: 0,
    gap: 0,
    overflow: "hidden",
    backgroundColor: color.surface,
    shadowColor: color.crust,
    shadowOpacity: 0.45,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 12,
  },
  composerInput: {
    minHeight: 44,
    maxHeight: 120,
    backgroundColor: "transparent",
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
  },
  askUserPrompt: {
    paddingHorizontal: space[3],
    paddingTop: space[3],
    paddingBottom: space[2],
    gap: space[2],
  },
  askUserTabsContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: space[1],
    paddingHorizontal: space[2],
    paddingTop: space[2],
    paddingBottom: space[1],
  },
  askUserTab: {
    maxWidth: 160,
    minHeight: 28,
    justifyContent: "center",
    borderRadius: radius.control,
    paddingHorizontal: space[2],
  },
  askUserTabActive: {
    backgroundColor: wash.row,
  },
  askUserTabLabel: {
    color: color.subtext,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  askUserTabLabelActive: {
    color: color.foreground,
  },
  askUserTabLabelReady: {
    color: color.accent,
  },
  askUserQuestion: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    fontWeight: "600",
    lineHeight: 20,
  },
  askUserContext: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    lineHeight: 18,
  },
  askUserInput: {
    minHeight: 44,
    maxHeight: 120,
    backgroundColor: "transparent",
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: color.border,
  },
  composerToolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: space[1],
    paddingHorizontal: space[2],
    paddingBottom: space[2],
  },
  selectorButton: {
    maxWidth: "42%",
    minHeight: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.control,
    backgroundColor: color.field,
    paddingHorizontal: space[2],
    paddingVertical: space[1],
  },
  selectorLabel: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  sendButton: {
    marginLeft: "auto",
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: color.accent,
  },
  sendButtonDisabled: {
    opacity: 0.4,
  },
  searchInput: {
    margin: space[3],
    marginBottom: 0,
    borderRadius: radius.control,
    backgroundColor: color.field,
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
  },
  groupLabel: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    fontWeight: "600",
    paddingHorizontal: space[4],
    paddingTop: space[3],
    paddingBottom: space[1],
  },
  listRow: {
    paddingHorizontal: space[4],
    paddingVertical: space[3],
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: color.border,
    gap: space[1],
  },
  listRowActive: {
    backgroundColor: wash.accentSoft,
  },
  listRowTitle: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
  },
  listRowMeta: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  choiceRow: {
    borderRadius: radius.panel,
    borderWidth: 1,
    borderColor: color.border,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
    gap: space[1],
  },
  choiceRowSelected: {
    borderColor: color.accent,
    backgroundColor: wash.accentSoft,
  },
});
