import { StyleSheet } from "react-native";

import { color, fontFamily, fontSize, radius, space, wash } from "../../../shared/theme";

export const aiStyles = StyleSheet.create({
  root: {
    flex: 1,
    minWidth: 0,
    backgroundColor: color.background,
  },
  header: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    gap: space[2],
    paddingHorizontal: space[4],
    borderBottomWidth: 1,
    borderBottomColor: color.border,
  },
  headerTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.md,
    fontWeight: "600",
  },
  subtitle: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    marginTop: 2,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: space[1],
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: space[4],
    paddingVertical: space[3],
    gap: space[3],
  },
  empty: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    textAlign: "center",
    padding: space[6],
  },
  banner: {
    borderRadius: radius.panel,
    borderWidth: 1,
    borderColor: color.error,
    backgroundColor: wash.dangerSoft,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
  },
  bannerText: {
    color: color.error,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
  },
  warningBanner: {
    borderRadius: radius.panel,
    borderWidth: 1,
    borderColor: color.warning,
    backgroundColor: wash.accentSoft,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
  },
  warningText: {
    color: color.warning,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
  },
  userBubble: {
    alignSelf: "flex-end",
    maxWidth: "92%",
    backgroundColor: wash.accentSoft,
    borderRadius: radius.panel,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
  },
  assistantBlock: {
    alignSelf: "stretch",
    gap: space[2],
  },
  messageText: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.chat,
    lineHeight: 20,
  },
  metaText: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  partCard: {
    borderRadius: radius.panel,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: color.border,
    backgroundColor: color.surface,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
    gap: space[1],
  },
  partTitle: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    fontWeight: "600",
  },
  rowActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: space[2],
    marginTop: space[1],
  },
  actionLabel: {
    color: color.accent,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    fontWeight: "600",
  },
  dangerLabel: {
    color: color.error,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    fontWeight: "600",
  },
  composer: {
    borderTopWidth: 1,
    borderTopColor: color.border,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
    gap: space[2],
    backgroundColor: color.background,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: space[1],
  },
  chip: {
    borderRadius: radius.pill,
    backgroundColor: wash.accentSoft,
    paddingHorizontal: space[2],
    paddingVertical: 2,
  },
  chipText: {
    color: color.accent,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  input: {
    minHeight: 44,
    maxHeight: 120,
    borderRadius: radius.control,
    backgroundColor: color.field,
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
  },
  composerToolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: space[2],
  },
  selectorButton: {
    borderRadius: radius.control,
    backgroundColor: color.surface,
    paddingHorizontal: space[2],
    paddingVertical: space[1],
  },
  selectorLabel: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  sendButton: {
    marginLeft: "auto",
    borderRadius: radius.control,
    backgroundColor: color.accent,
    paddingHorizontal: space[3],
    paddingVertical: space[1],
  },
  sendButtonDisabled: {
    opacity: 0.4,
  },
  sendLabel: {
    color: color.primaryForeground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    fontWeight: "600",
  },
  searchInput: {
    margin: space[3],
    marginBottom: 0,
    borderRadius: radius.control,
    backgroundColor: color.field,
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
  },
  groupLabel: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
    fontWeight: "600",
    paddingHorizontal: space[4],
    paddingTop: space[3],
    paddingBottom: space[1],
  },
  listRow: {
    paddingHorizontal: space[4],
    paddingVertical: space[3],
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: color.border,
    gap: space[1],
  },
  listRowActive: {
    backgroundColor: wash.accentSoft,
  },
  listRowTitle: {
    color: color.foreground,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
  },
  listRowMeta: {
    color: color.muted,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xxs,
  },
  choiceRow: {
    borderRadius: radius.panel,
    borderWidth: 1,
    borderColor: color.border,
    paddingHorizontal: space[3],
    paddingVertical: space[2],
  },
  choiceRowSelected: {
    borderColor: color.accent,
    backgroundColor: wash.accentSoft,
  },
});
